/** Wave 5 데이터베이스 공개 진입점이 신규 schema·query·repository를 노출하는지 검증한다 */
import {
  DrizzleAiQuestionProductionRepository,
  DrizzleAsyncDispatchOutboxRepository,
  DrizzleContentTtsReadinessQuery,
  DrizzleGeneratedQuestionDraftRepository,
  DrizzleGeneratedQuestionTtsScheduler,
  DrizzleQuestionProductionContextQuery,
  DrizzleTtsDurabilityRepository,
  DrizzleTtsOperationsQuery,
  DrizzleTtsRepository,
  DrizzleTtsRetryCoordinator,
  DrizzleTtsTargetAttachmentWriter,
  asyncDispatchOutbox,
  asyncDispatchPayloadKindEnum,
  assembleQuestionProductionContext,
  questionCandidateGroupEnum,
  questionCandidatePayloadStateEnum,
  questionCandidateReviewStatusEnum,
  questionProductionCandidates,
  questionProductionValidationStatusEnum,
  questionProductionValidations,
  questionValidationStageEnum,
  readQuestionProductionPresetPolicy,
  ttsAudioCache,
  ttsAudioCacheStatusEnum,
  ttsAudioGenerationClaimTtlMs,
  ttsItemStatusEnum,
  ttsItems,
  ttsJobStatusEnum,
  ttsJobs,
  ttsTargetKindEnum,
  ttsVoicePresets,
} from '@flex-thia/database';
import type * as Database from '@flex-thia/database';
import { describe, expect, expectTypeOf, it } from 'vitest';

type Wave5DatabaseBoundary = [
  Database.QuestionProductionTransaction,
  Database.GeneratedQuestionDraftWriter,
  Database.GeneratedQuestionTtsScheduler,
  Database.TtsDispatchOutboxWriter,
  Database.QuestionProductionContextRows,
  Database.TtsRepositoryTransaction,
  Database.CompleteTtsAudioInput,
  Database.TtsAudioClaimFinalization,
  Database.CompleteTtsAudioResult,
  Database.FailTtsAudioResult,
  Database.TtsTargetAttachmentWriter,
  Database.TtsRepository,
  Database.TtsOperationsJobListInput,
  Database.TtsOperationsItemListInput,
  Database.TtsOperationsQuery,
];

describe('Wave 5 database 공개 import', () => {
  it('패키지 루트가 schema·query·repository를 공개한다', () => {
    expectTypeOf<Wave5DatabaseBoundary>().toBeArray();
    expect([
      DrizzleAiQuestionProductionRepository,
      DrizzleAsyncDispatchOutboxRepository,
      DrizzleContentTtsReadinessQuery,
      DrizzleGeneratedQuestionDraftRepository,
      DrizzleGeneratedQuestionTtsScheduler,
      DrizzleQuestionProductionContextQuery,
      DrizzleTtsDurabilityRepository,
      DrizzleTtsOperationsQuery,
      DrizzleTtsRepository,
      DrizzleTtsRetryCoordinator,
      DrizzleTtsTargetAttachmentWriter,
      asyncDispatchOutbox,
      asyncDispatchPayloadKindEnum,
      assembleQuestionProductionContext,
      questionCandidateGroupEnum,
      questionCandidatePayloadStateEnum,
      questionCandidateReviewStatusEnum,
      questionProductionCandidates,
      questionProductionValidationStatusEnum,
      questionProductionValidations,
      questionValidationStageEnum,
      readQuestionProductionPresetPolicy,
      ttsAudioCache,
      ttsAudioCacheStatusEnum,
      ttsAudioGenerationClaimTtlMs,
      ttsItemStatusEnum,
      ttsItems,
      ttsJobStatusEnum,
      ttsJobs,
      ttsTargetKindEnum,
      ttsVoicePresets,
    ]).not.toContain(undefined);
  });
});
