/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuthenticatedRouteImport } from './app/routes/_authenticated'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as AuthenticatedLearnerRouteImport } from './app/routes/_authenticated._learner'
import { Route as AuthenticatedAdminRouteImport } from './app/routes/_authenticated.admin'
import { Route as LoginIndexRouteImport } from './app/routes/login.index'
import { Route as LoginMfaRouteImport } from './app/routes/login.mfa'
import { Route as AuthenticatedLearnerLearnRouteImport } from './app/routes/_authenticated._learner.learn'
import { Route as AuthenticatedLearnerQuestionsRouteImport } from './app/routes/_authenticated._learner.questions'
import { Route as AuthenticatedAdminEnrolledRouteImport } from './app/routes/_authenticated.admin._enrolled'
import { Route as AuthenticatedAdminEnrollmentRouteImport } from './app/routes/_authenticated.admin._enrollment'
import { Route as AuthenticatedLearnerQuestionsIndexRouteImport } from './app/routes/_authenticated._learner.questions.index'
import { Route as AuthenticatedLearnerQuestionsQuestionIdRouteImport } from './app/routes/_authenticated._learner.questions.$questionId'
import { Route as AuthenticatedAdminEnrolledIndexRouteImport } from './app/routes/_authenticated.admin._enrolled.index'
import { Route as AuthenticatedAdminEnrollmentTotpSetupRouteImport } from './app/routes/_authenticated.admin._enrollment.totp-setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearnerRoute = AuthenticatedLearnerRouteImport.update({
  id: '/_learner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginMfaRoute = LoginMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedLearnerLearnRoute =
  AuthenticatedLearnerLearnRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerQuestionsRoute =
  AuthenticatedLearnerQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedAdminEnrolledRoute =
  AuthenticatedAdminEnrolledRouteImport.update({
    id: '/_enrolled',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnrollmentRoute =
  AuthenticatedAdminEnrollmentRouteImport.update({
    id: '/_enrollment',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedLearnerQuestionsIndexRoute =
  AuthenticatedLearnerQuestionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLearnerQuestionsRoute,
  } as any)
const AuthenticatedLearnerQuestionsQuestionIdRoute =
  AuthenticatedLearnerQuestionsQuestionIdRouteImport.update({
    id: '/$questionId',
    path: '/$questionId',
    getParentRoute: () => AuthenticatedLearnerQuestionsRoute,
  } as any)
const AuthenticatedAdminEnrolledIndexRoute =
  AuthenticatedAdminEnrolledIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEnrolledRoute,
  } as any)
const AuthenticatedAdminEnrollmentTotpSetupRoute =
  AuthenticatedAdminEnrollmentTotpSetupRouteImport.update({
    id: '/totp-setup',
    path: '/totp-setup',
    getParentRoute: () => AuthenticatedAdminEnrollmentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/login/mfa': typeof LoginMfaRoute
  '/login/': typeof LoginIndexRoute
  '/learn': typeof AuthenticatedLearnerLearnRoute
  '/questions': typeof AuthenticatedLearnerQuestionsRouteWithChildren
  '/questions/$questionId': typeof AuthenticatedLearnerQuestionsQuestionIdRoute
  '/admin/totp-setup': typeof AuthenticatedAdminEnrollmentTotpSetupRoute
  '/questions/': typeof AuthenticatedLearnerQuestionsIndexRoute
  '/admin/': typeof AuthenticatedAdminEnrolledIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminEnrolledIndexRoute
  '/login/mfa': typeof LoginMfaRoute
  '/login': typeof LoginIndexRoute
  '/learn': typeof AuthenticatedLearnerLearnRoute
  '/questions/$questionId': typeof AuthenticatedLearnerQuestionsQuestionIdRoute
  '/admin/totp-setup': typeof AuthenticatedAdminEnrollmentTotpSetupRoute
  '/questions': typeof AuthenticatedLearnerQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_authenticated/_learner': typeof AuthenticatedLearnerRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/login/mfa': typeof LoginMfaRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/_learner/learn': typeof AuthenticatedLearnerLearnRoute
  '/_authenticated/_learner/questions': typeof AuthenticatedLearnerQuestionsRouteWithChildren
  '/_authenticated/admin/_enrolled': typeof AuthenticatedAdminEnrolledRouteWithChildren
  '/_authenticated/admin/_enrollment': typeof AuthenticatedAdminEnrollmentRouteWithChildren
  '/_authenticated/_learner/questions/$questionId': typeof AuthenticatedLearnerQuestionsQuestionIdRoute
  '/_authenticated/admin/_enrollment/totp-setup': typeof AuthenticatedAdminEnrollmentTotpSetupRoute
  '/_authenticated/_learner/questions/': typeof AuthenticatedLearnerQuestionsIndexRoute
  '/_authenticated/admin/_enrolled/': typeof AuthenticatedAdminEnrolledIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/login/mfa'
    | '/login/'
    | '/learn'
    | '/questions'
    | '/questions/$questionId'
    | '/admin/totp-setup'
    | '/questions/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login/mfa'
    | '/login'
    | '/learn'
    | '/questions/$questionId'
    | '/admin/totp-setup'
    | '/questions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_learner'
    | '/_authenticated/admin'
    | '/login/mfa'
    | '/login/'
    | '/_authenticated/_learner/learn'
    | '/_authenticated/_learner/questions'
    | '/_authenticated/admin/_enrolled'
    | '/_authenticated/admin/_enrollment'
    | '/_authenticated/_learner/questions/$questionId'
    | '/_authenticated/admin/_enrollment/totp-setup'
    | '/_authenticated/_learner/questions/'
    | '/_authenticated/admin/_enrolled/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_learner': {
      id: '/_authenticated/_learner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLearnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/mfa': {
      id: '/login/mfa'
      path: '/mfa'
      fullPath: '/login/mfa'
      preLoaderRoute: typeof LoginMfaRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/_learner/learn': {
      id: '/_authenticated/_learner/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnerLearnRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/questions': {
      id: '/_authenticated/_learner/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedLearnerQuestionsRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/admin/_enrolled': {
      id: '/_authenticated/admin/_enrolled'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/_enrollment': {
      id: '/_authenticated/admin/_enrollment'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminEnrollmentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_learner/questions/': {
      id: '/_authenticated/_learner/questions/'
      path: '/'
      fullPath: '/questions/'
      preLoaderRoute: typeof AuthenticatedLearnerQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedLearnerQuestionsRoute
    }
    '/_authenticated/_learner/questions/$questionId': {
      id: '/_authenticated/_learner/questions/$questionId'
      path: '/$questionId'
      fullPath: '/questions/$questionId'
      preLoaderRoute: typeof AuthenticatedLearnerQuestionsQuestionIdRouteImport
      parentRoute: typeof AuthenticatedLearnerQuestionsRoute
    }
    '/_authenticated/admin/_enrolled/': {
      id: '/_authenticated/admin/_enrolled/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledRoute
    }
    '/_authenticated/admin/_enrollment/totp-setup': {
      id: '/_authenticated/admin/_enrollment/totp-setup'
      path: '/totp-setup'
      fullPath: '/admin/totp-setup'
      preLoaderRoute: typeof AuthenticatedAdminEnrollmentTotpSetupRouteImport
      parentRoute: typeof AuthenticatedAdminEnrollmentRoute
    }
  }
}

interface AuthenticatedLearnerQuestionsRouteChildren {
  AuthenticatedLearnerQuestionsQuestionIdRoute: typeof AuthenticatedLearnerQuestionsQuestionIdRoute
  AuthenticatedLearnerQuestionsIndexRoute: typeof AuthenticatedLearnerQuestionsIndexRoute
}

const AuthenticatedLearnerQuestionsRouteChildren: AuthenticatedLearnerQuestionsRouteChildren =
  {
    AuthenticatedLearnerQuestionsQuestionIdRoute:
      AuthenticatedLearnerQuestionsQuestionIdRoute,
    AuthenticatedLearnerQuestionsIndexRoute:
      AuthenticatedLearnerQuestionsIndexRoute,
  }

const AuthenticatedLearnerQuestionsRouteWithChildren =
  AuthenticatedLearnerQuestionsRoute._addFileChildren(
    AuthenticatedLearnerQuestionsRouteChildren,
  )

interface AuthenticatedLearnerRouteChildren {
  AuthenticatedLearnerLearnRoute: typeof AuthenticatedLearnerLearnRoute
  AuthenticatedLearnerQuestionsRoute: typeof AuthenticatedLearnerQuestionsRouteWithChildren
}

const AuthenticatedLearnerRouteChildren: AuthenticatedLearnerRouteChildren = {
  AuthenticatedLearnerLearnRoute: AuthenticatedLearnerLearnRoute,
  AuthenticatedLearnerQuestionsRoute:
    AuthenticatedLearnerQuestionsRouteWithChildren,
}

const AuthenticatedLearnerRouteWithChildren =
  AuthenticatedLearnerRoute._addFileChildren(AuthenticatedLearnerRouteChildren)

interface AuthenticatedAdminEnrolledRouteChildren {
  AuthenticatedAdminEnrolledIndexRoute: typeof AuthenticatedAdminEnrolledIndexRoute
}

const AuthenticatedAdminEnrolledRouteChildren: AuthenticatedAdminEnrolledRouteChildren =
  {
    AuthenticatedAdminEnrolledIndexRoute: AuthenticatedAdminEnrolledIndexRoute,
  }

const AuthenticatedAdminEnrolledRouteWithChildren =
  AuthenticatedAdminEnrolledRoute._addFileChildren(
    AuthenticatedAdminEnrolledRouteChildren,
  )

interface AuthenticatedAdminEnrollmentRouteChildren {
  AuthenticatedAdminEnrollmentTotpSetupRoute: typeof AuthenticatedAdminEnrollmentTotpSetupRoute
}

const AuthenticatedAdminEnrollmentRouteChildren: AuthenticatedAdminEnrollmentRouteChildren =
  {
    AuthenticatedAdminEnrollmentTotpSetupRoute:
      AuthenticatedAdminEnrollmentTotpSetupRoute,
  }

const AuthenticatedAdminEnrollmentRouteWithChildren =
  AuthenticatedAdminEnrollmentRoute._addFileChildren(
    AuthenticatedAdminEnrollmentRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEnrolledRoute: typeof AuthenticatedAdminEnrolledRouteWithChildren
  AuthenticatedAdminEnrollmentRoute: typeof AuthenticatedAdminEnrollmentRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEnrolledRoute: AuthenticatedAdminEnrolledRouteWithChildren,
  AuthenticatedAdminEnrollmentRoute:
    AuthenticatedAdminEnrollmentRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLearnerRoute: typeof AuthenticatedLearnerRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLearnerRoute: AuthenticatedLearnerRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginMfaRoute: typeof LoginMfaRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginMfaRoute: LoginMfaRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
