/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuthenticatedRouteImport } from './app/routes/_authenticated'
import { Route as ForbiddenRouteImport } from './app/routes/forbidden'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as AuthenticatedLearnerRouteImport } from './app/routes/_authenticated._learner'
import { Route as AuthenticatedAdminRouteImport } from './app/routes/_authenticated.admin'
import { Route as LoginIndexRouteImport } from './app/routes/login.index'
import { Route as LoginChallengeRouteImport } from './app/routes/login.challenge'
import { Route as LoginConfirmRouteImport } from './app/routes/login.confirm'
import { Route as LoginMfaRouteImport } from './app/routes/login.mfa'
import { Route as AuthenticatedLearnerHistoryRouteImport } from './app/routes/_authenticated._learner.history'
import { Route as AuthenticatedLearnerLearnRouteImport } from './app/routes/_authenticated._learner.learn'
import { Route as AuthenticatedLearnerQuestionsRouteImport } from './app/routes/_authenticated._learner.questions'
import { Route as AuthenticatedLearnerVocabulariesRouteImport } from './app/routes/_authenticated._learner.vocabularies'
import { Route as AuthenticatedAdminEnrolledRouteImport } from './app/routes/_authenticated.admin._enrolled'
import { Route as AuthenticatedAdminEnrollmentRouteImport } from './app/routes/_authenticated.admin._enrollment'
import { Route as AuthenticatedLearnerConceptsIndexRouteImport } from './app/routes/_authenticated._learner.concepts.index'
import { Route as AuthenticatedLearnerConceptsConceptIdRouteImport } from './app/routes/_authenticated._learner.concepts.$conceptId'
import { Route as AuthenticatedLearnerPracticeIndexRouteImport } from './app/routes/_authenticated._learner.practice.index'
import { Route as AuthenticatedLearnerPracticeSessionIdRouteImport } from './app/routes/_authenticated._learner.practice.$sessionId'
import { Route as AuthenticatedLearnerQuestionsIndexRouteImport } from './app/routes/_authenticated._learner.questions.index'
import { Route as AuthenticatedLearnerQuestionsQuestionIdRouteImport } from './app/routes/_authenticated._learner.questions.$questionId'
import { Route as AuthenticatedLearnerVocabulariesIndexRouteImport } from './app/routes/_authenticated._learner.vocabularies.index'
import { Route as AuthenticatedLearnerVocabulariesVocabularyIdRouteImport } from './app/routes/_authenticated._learner.vocabularies.$vocabularyId'
import { Route as AuthenticatedLearnerWordbooksIndexRouteImport } from './app/routes/_authenticated._learner.wordbooks.index'
import { Route as AuthenticatedLearnerWordbooksWordbookIdRouteImport } from './app/routes/_authenticated._learner.wordbooks.$wordbookId'
import { Route as AuthenticatedAdminEnrolledIndexRouteImport } from './app/routes/_authenticated.admin._enrolled.index'
import { Route as AuthenticatedAdminEnrolledContentErrorReportsRouteImport } from './app/routes/_authenticated.admin._enrolled.content-error-reports'
import { Route as AuthenticatedAdminEnrolledContentImportsRouteImport } from './app/routes/_authenticated.admin._enrolled.content-imports'
import { Route as AuthenticatedAdminEnrolledQuestionsRouteImport } from './app/routes/_authenticated.admin._enrolled.questions'
import { Route as AuthenticatedAdminEnrolledUsersRouteImport } from './app/routes/_authenticated.admin._enrolled.users'
import { Route as AuthenticatedAdminEnrolledVocabulariesRouteImport } from './app/routes/_authenticated.admin._enrolled.vocabularies'
import { Route as AuthenticatedAdminEnrollmentTotpSetupRouteImport } from './app/routes/_authenticated.admin._enrollment.totp-setup'
import { Route as AuthenticatedLearnerPracticeSessionIdResultRouteImport } from './app/routes/_authenticated._learner.practice.$sessionId.result'
import { Route as AuthenticatedAdminEnrolledConceptsIndexRouteImport } from './app/routes/_authenticated.admin._enrolled.concepts.index'
import { Route as AuthenticatedAdminEnrolledConceptsConceptIdRouteImport } from './app/routes/_authenticated.admin._enrolled.concepts.$conceptId'
import { Route as AuthenticatedAdminEnrolledContentImportsIndexRouteImport } from './app/routes/_authenticated.admin._enrolled.content-imports.index'
import { Route as AuthenticatedAdminEnrolledContentImportsImportIdRouteImport } from './app/routes/_authenticated.admin._enrolled.content-imports.$importId'
import { Route as AuthenticatedAdminEnrolledQuestionsIndexRouteImport } from './app/routes/_authenticated.admin._enrolled.questions.index'
import { Route as AuthenticatedAdminEnrolledQuestionsQuestionIdRouteImport } from './app/routes/_authenticated.admin._enrolled.questions.$questionId'
import { Route as AuthenticatedAdminEnrolledVocabulariesIndexRouteImport } from './app/routes/_authenticated.admin._enrolled.vocabularies.index'
import { Route as AuthenticatedAdminEnrolledVocabulariesVocabularyIdRouteImport } from './app/routes/_authenticated.admin._enrolled.vocabularies.$vocabularyId'
import { Route as AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRouteImport } from './app/routes/_authenticated.admin._enrolled.questions.$questionId.index'
import { Route as AuthenticatedAdminEnrolledQuestionsQuestionIdVersionsVersionIdReplaceRouteImport } from './app/routes/_authenticated.admin._enrolled.questions.$questionId.versions.$versionId.replace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearnerRoute = AuthenticatedLearnerRouteImport.update({
  id: '/_learner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginChallengeRoute = LoginChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => LoginRoute,
} as any)
const LoginConfirmRoute = LoginConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => LoginRoute,
} as any)
const LoginMfaRoute = LoginMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedLearnerHistoryRoute =
  AuthenticatedLearnerHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerLearnRoute =
  AuthenticatedLearnerLearnRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerQuestionsRoute =
  AuthenticatedLearnerQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerVocabulariesRoute =
  AuthenticatedLearnerVocabulariesRouteImport.update({
    id: '/vocabularies',
    path: '/vocabularies',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedAdminEnrolledRoute =
  AuthenticatedAdminEnrolledRouteImport.update({
    id: '/_enrolled',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnrollmentRoute =
  AuthenticatedAdminEnrollmentRouteImport.update({
    id: '/_enrollment',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedLearnerConceptsIndexRoute =
  AuthenticatedLearnerConceptsIndexRouteImport.update({
    id: '/concepts/',
    path: '/concepts/',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerConceptsConceptIdRoute =
  AuthenticatedLearnerConceptsConceptIdRouteImport.update({
    id: '/concepts/$conceptId',
    path: '/concepts/$conceptId',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerPracticeIndexRoute =
  AuthenticatedLearnerPracticeIndexRouteImport.update({
    id: '/practice/',
    path: '/practice/',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerPracticeSessionIdRoute =
  AuthenticatedLearnerPracticeSessionIdRouteImport.update({
    id: '/practice/$sessionId',
    path: '/practice/$sessionId',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerQuestionsIndexRoute =
  AuthenticatedLearnerQuestionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLearnerQuestionsRoute,
  } as any)
const AuthenticatedLearnerQuestionsQuestionIdRoute =
  AuthenticatedLearnerQuestionsQuestionIdRouteImport.update({
    id: '/$questionId',
    path: '/$questionId',
    getParentRoute: () => AuthenticatedLearnerQuestionsRoute,
  } as any)
const AuthenticatedLearnerVocabulariesIndexRoute =
  AuthenticatedLearnerVocabulariesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLearnerVocabulariesRoute,
  } as any)
const AuthenticatedLearnerVocabulariesVocabularyIdRoute =
  AuthenticatedLearnerVocabulariesVocabularyIdRouteImport.update({
    id: '/$vocabularyId',
    path: '/$vocabularyId',
    getParentRoute: () => AuthenticatedLearnerVocabulariesRoute,
  } as any)
const AuthenticatedLearnerWordbooksIndexRoute =
  AuthenticatedLearnerWordbooksIndexRouteImport.update({
    id: '/wordbooks/',
    path: '/wordbooks/',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerWordbooksWordbookIdRoute =
  AuthenticatedLearnerWordbooksWordbookIdRouteImport.update({
    id: '/wordbooks/$wordbookId',
    path: '/wordbooks/$wordbookId',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedAdminEnrolledIndexRoute =
  AuthenticatedAdminEnrolledIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEnrolledRoute,
  } as any)
const AuthenticatedAdminEnrolledContentErrorReportsRoute =
  AuthenticatedAdminEnrolledContentErrorReportsRouteImport.update({
    id: '/content-error-reports',
    path: '/content-error-reports',
    getParentRoute: () => AuthenticatedAdminEnrolledRoute,
  } as any)
const AuthenticatedAdminEnrolledContentImportsRoute =
  AuthenticatedAdminEnrolledContentImportsRouteImport.update({
    id: '/content-imports',
    path: '/content-imports',
    getParentRoute: () => AuthenticatedAdminEnrolledRoute,
  } as any)
const AuthenticatedAdminEnrolledQuestionsRoute =
  AuthenticatedAdminEnrolledQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminEnrolledRoute,
  } as any)
const AuthenticatedAdminEnrolledUsersRoute =
  AuthenticatedAdminEnrolledUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAdminEnrolledRoute,
  } as any)
const AuthenticatedAdminEnrolledVocabulariesRoute =
  AuthenticatedAdminEnrolledVocabulariesRouteImport.update({
    id: '/vocabularies',
    path: '/vocabularies',
    getParentRoute: () => AuthenticatedAdminEnrolledRoute,
  } as any)
const AuthenticatedAdminEnrollmentTotpSetupRoute =
  AuthenticatedAdminEnrollmentTotpSetupRouteImport.update({
    id: '/totp-setup',
    path: '/totp-setup',
    getParentRoute: () => AuthenticatedAdminEnrollmentRoute,
  } as any)
const AuthenticatedLearnerPracticeSessionIdResultRoute =
  AuthenticatedLearnerPracticeSessionIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => AuthenticatedLearnerPracticeSessionIdRoute,
  } as any)
const AuthenticatedAdminEnrolledConceptsIndexRoute =
  AuthenticatedAdminEnrolledConceptsIndexRouteImport.update({
    id: '/concepts/',
    path: '/concepts/',
    getParentRoute: () => AuthenticatedAdminEnrolledRoute,
  } as any)
const AuthenticatedAdminEnrolledConceptsConceptIdRoute =
  AuthenticatedAdminEnrolledConceptsConceptIdRouteImport.update({
    id: '/concepts/$conceptId',
    path: '/concepts/$conceptId',
    getParentRoute: () => AuthenticatedAdminEnrolledRoute,
  } as any)
const AuthenticatedAdminEnrolledContentImportsIndexRoute =
  AuthenticatedAdminEnrolledContentImportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEnrolledContentImportsRoute,
  } as any)
const AuthenticatedAdminEnrolledContentImportsImportIdRoute =
  AuthenticatedAdminEnrolledContentImportsImportIdRouteImport.update({
    id: '/$importId',
    path: '/$importId',
    getParentRoute: () => AuthenticatedAdminEnrolledContentImportsRoute,
  } as any)
const AuthenticatedAdminEnrolledQuestionsIndexRoute =
  AuthenticatedAdminEnrolledQuestionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEnrolledQuestionsRoute,
  } as any)
const AuthenticatedAdminEnrolledQuestionsQuestionIdRoute =
  AuthenticatedAdminEnrolledQuestionsQuestionIdRouteImport.update({
    id: '/$questionId',
    path: '/$questionId',
    getParentRoute: () => AuthenticatedAdminEnrolledQuestionsRoute,
  } as any)
const AuthenticatedAdminEnrolledVocabulariesIndexRoute =
  AuthenticatedAdminEnrolledVocabulariesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEnrolledVocabulariesRoute,
  } as any)
const AuthenticatedAdminEnrolledVocabulariesVocabularyIdRoute =
  AuthenticatedAdminEnrolledVocabulariesVocabularyIdRouteImport.update({
    id: '/$vocabularyId',
    path: '/$vocabularyId',
    getParentRoute: () => AuthenticatedAdminEnrolledVocabulariesRoute,
  } as any)
const AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute =
  AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEnrolledQuestionsQuestionIdRoute,
  } as any)
const AuthenticatedAdminEnrolledQuestionsQuestionIdVersionsVersionIdReplaceRoute =
  AuthenticatedAdminEnrolledQuestionsQuestionIdVersionsVersionIdReplaceRouteImport.update(
    {
      id: '/versions/$versionId/replace',
      path: '/versions/$versionId/replace',
      getParentRoute: () => AuthenticatedAdminEnrolledQuestionsQuestionIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/login/challenge': typeof LoginChallengeRoute
  '/login/confirm': typeof LoginConfirmRoute
  '/login/mfa': typeof LoginMfaRoute
  '/login/': typeof LoginIndexRoute
  '/history': typeof AuthenticatedLearnerHistoryRoute
  '/learn': typeof AuthenticatedLearnerLearnRoute
  '/questions': typeof AuthenticatedLearnerQuestionsRouteWithChildren
  '/vocabularies': typeof AuthenticatedLearnerVocabulariesRouteWithChildren
  '/concepts/$conceptId': typeof AuthenticatedLearnerConceptsConceptIdRoute
  '/practice/$sessionId': typeof AuthenticatedLearnerPracticeSessionIdRouteWithChildren
  '/questions/$questionId': typeof AuthenticatedLearnerQuestionsQuestionIdRoute
  '/vocabularies/$vocabularyId': typeof AuthenticatedLearnerVocabulariesVocabularyIdRoute
  '/wordbooks/$wordbookId': typeof AuthenticatedLearnerWordbooksWordbookIdRoute
  '/admin/content-error-reports': typeof AuthenticatedAdminEnrolledContentErrorReportsRoute
  '/admin/content-imports': typeof AuthenticatedAdminEnrolledContentImportsRouteWithChildren
  '/admin/questions': typeof AuthenticatedAdminEnrolledQuestionsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminEnrolledUsersRoute
  '/admin/vocabularies': typeof AuthenticatedAdminEnrolledVocabulariesRouteWithChildren
  '/admin/totp-setup': typeof AuthenticatedAdminEnrollmentTotpSetupRoute
  '/concepts/': typeof AuthenticatedLearnerConceptsIndexRoute
  '/practice/': typeof AuthenticatedLearnerPracticeIndexRoute
  '/questions/': typeof AuthenticatedLearnerQuestionsIndexRoute
  '/vocabularies/': typeof AuthenticatedLearnerVocabulariesIndexRoute
  '/wordbooks/': typeof AuthenticatedLearnerWordbooksIndexRoute
  '/admin/': typeof AuthenticatedAdminEnrolledIndexRoute
  '/practice/$sessionId/result': typeof AuthenticatedLearnerPracticeSessionIdResultRoute
  '/admin/concepts/$conceptId': typeof AuthenticatedAdminEnrolledConceptsConceptIdRoute
  '/admin/content-imports/$importId': typeof AuthenticatedAdminEnrolledContentImportsImportIdRoute
  '/admin/questions/$questionId': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdRouteWithChildren
  '/admin/vocabularies/$vocabularyId': typeof AuthenticatedAdminEnrolledVocabulariesVocabularyIdRoute
  '/admin/concepts/': typeof AuthenticatedAdminEnrolledConceptsIndexRoute
  '/admin/content-imports/': typeof AuthenticatedAdminEnrolledContentImportsIndexRoute
  '/admin/questions/': typeof AuthenticatedAdminEnrolledQuestionsIndexRoute
  '/admin/vocabularies/': typeof AuthenticatedAdminEnrolledVocabulariesIndexRoute
  '/admin/questions/$questionId/': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute
  '/admin/questions/$questionId/versions/$versionId/replace': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdVersionsVersionIdReplaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/admin': typeof AuthenticatedAdminEnrolledIndexRoute
  '/login/challenge': typeof LoginChallengeRoute
  '/login/confirm': typeof LoginConfirmRoute
  '/login/mfa': typeof LoginMfaRoute
  '/login': typeof LoginIndexRoute
  '/history': typeof AuthenticatedLearnerHistoryRoute
  '/learn': typeof AuthenticatedLearnerLearnRoute
  '/concepts/$conceptId': typeof AuthenticatedLearnerConceptsConceptIdRoute
  '/practice/$sessionId': typeof AuthenticatedLearnerPracticeSessionIdRouteWithChildren
  '/questions/$questionId': typeof AuthenticatedLearnerQuestionsQuestionIdRoute
  '/vocabularies/$vocabularyId': typeof AuthenticatedLearnerVocabulariesVocabularyIdRoute
  '/wordbooks/$wordbookId': typeof AuthenticatedLearnerWordbooksWordbookIdRoute
  '/admin/content-error-reports': typeof AuthenticatedAdminEnrolledContentErrorReportsRoute
  '/admin/users': typeof AuthenticatedAdminEnrolledUsersRoute
  '/admin/totp-setup': typeof AuthenticatedAdminEnrollmentTotpSetupRoute
  '/concepts': typeof AuthenticatedLearnerConceptsIndexRoute
  '/practice': typeof AuthenticatedLearnerPracticeIndexRoute
  '/questions': typeof AuthenticatedLearnerQuestionsIndexRoute
  '/vocabularies': typeof AuthenticatedLearnerVocabulariesIndexRoute
  '/wordbooks': typeof AuthenticatedLearnerWordbooksIndexRoute
  '/practice/$sessionId/result': typeof AuthenticatedLearnerPracticeSessionIdResultRoute
  '/admin/concepts/$conceptId': typeof AuthenticatedAdminEnrolledConceptsConceptIdRoute
  '/admin/content-imports/$importId': typeof AuthenticatedAdminEnrolledContentImportsImportIdRoute
  '/admin/vocabularies/$vocabularyId': typeof AuthenticatedAdminEnrolledVocabulariesVocabularyIdRoute
  '/admin/concepts': typeof AuthenticatedAdminEnrolledConceptsIndexRoute
  '/admin/content-imports': typeof AuthenticatedAdminEnrolledContentImportsIndexRoute
  '/admin/questions': typeof AuthenticatedAdminEnrolledQuestionsIndexRoute
  '/admin/vocabularies': typeof AuthenticatedAdminEnrolledVocabulariesIndexRoute
  '/admin/questions/$questionId': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute
  '/admin/questions/$questionId/versions/$versionId/replace': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdVersionsVersionIdReplaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRouteWithChildren
  '/_authenticated/_learner': typeof AuthenticatedLearnerRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/login/challenge': typeof LoginChallengeRoute
  '/login/confirm': typeof LoginConfirmRoute
  '/login/mfa': typeof LoginMfaRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/_learner/history': typeof AuthenticatedLearnerHistoryRoute
  '/_authenticated/_learner/learn': typeof AuthenticatedLearnerLearnRoute
  '/_authenticated/_learner/questions': typeof AuthenticatedLearnerQuestionsRouteWithChildren
  '/_authenticated/_learner/vocabularies': typeof AuthenticatedLearnerVocabulariesRouteWithChildren
  '/_authenticated/admin/_enrolled': typeof AuthenticatedAdminEnrolledRouteWithChildren
  '/_authenticated/admin/_enrollment': typeof AuthenticatedAdminEnrollmentRouteWithChildren
  '/_authenticated/_learner/concepts/$conceptId': typeof AuthenticatedLearnerConceptsConceptIdRoute
  '/_authenticated/_learner/practice/$sessionId': typeof AuthenticatedLearnerPracticeSessionIdRouteWithChildren
  '/_authenticated/_learner/questions/$questionId': typeof AuthenticatedLearnerQuestionsQuestionIdRoute
  '/_authenticated/_learner/vocabularies/$vocabularyId': typeof AuthenticatedLearnerVocabulariesVocabularyIdRoute
  '/_authenticated/_learner/wordbooks/$wordbookId': typeof AuthenticatedLearnerWordbooksWordbookIdRoute
  '/_authenticated/admin/_enrolled/content-error-reports': typeof AuthenticatedAdminEnrolledContentErrorReportsRoute
  '/_authenticated/admin/_enrolled/content-imports': typeof AuthenticatedAdminEnrolledContentImportsRouteWithChildren
  '/_authenticated/admin/_enrolled/questions': typeof AuthenticatedAdminEnrolledQuestionsRouteWithChildren
  '/_authenticated/admin/_enrolled/users': typeof AuthenticatedAdminEnrolledUsersRoute
  '/_authenticated/admin/_enrolled/vocabularies': typeof AuthenticatedAdminEnrolledVocabulariesRouteWithChildren
  '/_authenticated/admin/_enrollment/totp-setup': typeof AuthenticatedAdminEnrollmentTotpSetupRoute
  '/_authenticated/_learner/concepts/': typeof AuthenticatedLearnerConceptsIndexRoute
  '/_authenticated/_learner/practice/': typeof AuthenticatedLearnerPracticeIndexRoute
  '/_authenticated/_learner/questions/': typeof AuthenticatedLearnerQuestionsIndexRoute
  '/_authenticated/_learner/vocabularies/': typeof AuthenticatedLearnerVocabulariesIndexRoute
  '/_authenticated/_learner/wordbooks/': typeof AuthenticatedLearnerWordbooksIndexRoute
  '/_authenticated/admin/_enrolled/': typeof AuthenticatedAdminEnrolledIndexRoute
  '/_authenticated/_learner/practice/$sessionId/result': typeof AuthenticatedLearnerPracticeSessionIdResultRoute
  '/_authenticated/admin/_enrolled/concepts/$conceptId': typeof AuthenticatedAdminEnrolledConceptsConceptIdRoute
  '/_authenticated/admin/_enrolled/content-imports/$importId': typeof AuthenticatedAdminEnrolledContentImportsImportIdRoute
  '/_authenticated/admin/_enrolled/questions/$questionId': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdRouteWithChildren
  '/_authenticated/admin/_enrolled/vocabularies/$vocabularyId': typeof AuthenticatedAdminEnrolledVocabulariesVocabularyIdRoute
  '/_authenticated/admin/_enrolled/concepts/': typeof AuthenticatedAdminEnrolledConceptsIndexRoute
  '/_authenticated/admin/_enrolled/content-imports/': typeof AuthenticatedAdminEnrolledContentImportsIndexRoute
  '/_authenticated/admin/_enrolled/questions/': typeof AuthenticatedAdminEnrolledQuestionsIndexRoute
  '/_authenticated/admin/_enrolled/vocabularies/': typeof AuthenticatedAdminEnrolledVocabulariesIndexRoute
  '/_authenticated/admin/_enrolled/questions/$questionId/': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute
  '/_authenticated/admin/_enrolled/questions/$questionId/versions/$versionId/replace': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdVersionsVersionIdReplaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/admin'
    | '/login/challenge'
    | '/login/confirm'
    | '/login/mfa'
    | '/login/'
    | '/history'
    | '/learn'
    | '/questions'
    | '/vocabularies'
    | '/concepts/$conceptId'
    | '/practice/$sessionId'
    | '/questions/$questionId'
    | '/vocabularies/$vocabularyId'
    | '/wordbooks/$wordbookId'
    | '/admin/content-error-reports'
    | '/admin/content-imports'
    | '/admin/questions'
    | '/admin/users'
    | '/admin/vocabularies'
    | '/admin/totp-setup'
    | '/concepts/'
    | '/practice/'
    | '/questions/'
    | '/vocabularies/'
    | '/wordbooks/'
    | '/admin/'
    | '/practice/$sessionId/result'
    | '/admin/concepts/$conceptId'
    | '/admin/content-imports/$importId'
    | '/admin/questions/$questionId'
    | '/admin/vocabularies/$vocabularyId'
    | '/admin/concepts/'
    | '/admin/content-imports/'
    | '/admin/questions/'
    | '/admin/vocabularies/'
    | '/admin/questions/$questionId/'
    | '/admin/questions/$questionId/versions/$versionId/replace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/admin'
    | '/login/challenge'
    | '/login/confirm'
    | '/login/mfa'
    | '/login'
    | '/history'
    | '/learn'
    | '/concepts/$conceptId'
    | '/practice/$sessionId'
    | '/questions/$questionId'
    | '/vocabularies/$vocabularyId'
    | '/wordbooks/$wordbookId'
    | '/admin/content-error-reports'
    | '/admin/users'
    | '/admin/totp-setup'
    | '/concepts'
    | '/practice'
    | '/questions'
    | '/vocabularies'
    | '/wordbooks'
    | '/practice/$sessionId/result'
    | '/admin/concepts/$conceptId'
    | '/admin/content-imports/$importId'
    | '/admin/vocabularies/$vocabularyId'
    | '/admin/concepts'
    | '/admin/content-imports'
    | '/admin/questions'
    | '/admin/vocabularies'
    | '/admin/questions/$questionId'
    | '/admin/questions/$questionId/versions/$versionId/replace'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forbidden'
    | '/login'
    | '/_authenticated/_learner'
    | '/_authenticated/admin'
    | '/login/challenge'
    | '/login/confirm'
    | '/login/mfa'
    | '/login/'
    | '/_authenticated/_learner/history'
    | '/_authenticated/_learner/learn'
    | '/_authenticated/_learner/questions'
    | '/_authenticated/_learner/vocabularies'
    | '/_authenticated/admin/_enrolled'
    | '/_authenticated/admin/_enrollment'
    | '/_authenticated/_learner/concepts/$conceptId'
    | '/_authenticated/_learner/practice/$sessionId'
    | '/_authenticated/_learner/questions/$questionId'
    | '/_authenticated/_learner/vocabularies/$vocabularyId'
    | '/_authenticated/_learner/wordbooks/$wordbookId'
    | '/_authenticated/admin/_enrolled/content-error-reports'
    | '/_authenticated/admin/_enrolled/content-imports'
    | '/_authenticated/admin/_enrolled/questions'
    | '/_authenticated/admin/_enrolled/users'
    | '/_authenticated/admin/_enrolled/vocabularies'
    | '/_authenticated/admin/_enrollment/totp-setup'
    | '/_authenticated/_learner/concepts/'
    | '/_authenticated/_learner/practice/'
    | '/_authenticated/_learner/questions/'
    | '/_authenticated/_learner/vocabularies/'
    | '/_authenticated/_learner/wordbooks/'
    | '/_authenticated/admin/_enrolled/'
    | '/_authenticated/_learner/practice/$sessionId/result'
    | '/_authenticated/admin/_enrolled/concepts/$conceptId'
    | '/_authenticated/admin/_enrolled/content-imports/$importId'
    | '/_authenticated/admin/_enrolled/questions/$questionId'
    | '/_authenticated/admin/_enrolled/vocabularies/$vocabularyId'
    | '/_authenticated/admin/_enrolled/concepts/'
    | '/_authenticated/admin/_enrolled/content-imports/'
    | '/_authenticated/admin/_enrolled/questions/'
    | '/_authenticated/admin/_enrolled/vocabularies/'
    | '/_authenticated/admin/_enrolled/questions/$questionId/'
    | '/_authenticated/admin/_enrolled/questions/$questionId/versions/$versionId/replace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_learner': {
      id: '/_authenticated/_learner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLearnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/challenge': {
      id: '/login/challenge'
      path: '/challenge'
      fullPath: '/login/challenge'
      preLoaderRoute: typeof LoginChallengeRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/confirm': {
      id: '/login/confirm'
      path: '/confirm'
      fullPath: '/login/confirm'
      preLoaderRoute: typeof LoginConfirmRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/mfa': {
      id: '/login/mfa'
      path: '/mfa'
      fullPath: '/login/mfa'
      preLoaderRoute: typeof LoginMfaRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/_learner/history': {
      id: '/_authenticated/_learner/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedLearnerHistoryRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/learn': {
      id: '/_authenticated/_learner/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnerLearnRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/questions': {
      id: '/_authenticated/_learner/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedLearnerQuestionsRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/vocabularies': {
      id: '/_authenticated/_learner/vocabularies'
      path: '/vocabularies'
      fullPath: '/vocabularies'
      preLoaderRoute: typeof AuthenticatedLearnerVocabulariesRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/admin/_enrolled': {
      id: '/_authenticated/admin/_enrolled'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/_enrollment': {
      id: '/_authenticated/admin/_enrollment'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminEnrollmentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_learner/concepts/': {
      id: '/_authenticated/_learner/concepts/'
      path: '/concepts'
      fullPath: '/concepts/'
      preLoaderRoute: typeof AuthenticatedLearnerConceptsIndexRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/concepts/$conceptId': {
      id: '/_authenticated/_learner/concepts/$conceptId'
      path: '/concepts/$conceptId'
      fullPath: '/concepts/$conceptId'
      preLoaderRoute: typeof AuthenticatedLearnerConceptsConceptIdRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/practice/': {
      id: '/_authenticated/_learner/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedLearnerPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/practice/$sessionId': {
      id: '/_authenticated/_learner/practice/$sessionId'
      path: '/practice/$sessionId'
      fullPath: '/practice/$sessionId'
      preLoaderRoute: typeof AuthenticatedLearnerPracticeSessionIdRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/questions/': {
      id: '/_authenticated/_learner/questions/'
      path: '/'
      fullPath: '/questions/'
      preLoaderRoute: typeof AuthenticatedLearnerQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedLearnerQuestionsRoute
    }
    '/_authenticated/_learner/questions/$questionId': {
      id: '/_authenticated/_learner/questions/$questionId'
      path: '/$questionId'
      fullPath: '/questions/$questionId'
      preLoaderRoute: typeof AuthenticatedLearnerQuestionsQuestionIdRouteImport
      parentRoute: typeof AuthenticatedLearnerQuestionsRoute
    }
    '/_authenticated/_learner/vocabularies/': {
      id: '/_authenticated/_learner/vocabularies/'
      path: '/'
      fullPath: '/vocabularies/'
      preLoaderRoute: typeof AuthenticatedLearnerVocabulariesIndexRouteImport
      parentRoute: typeof AuthenticatedLearnerVocabulariesRoute
    }
    '/_authenticated/_learner/vocabularies/$vocabularyId': {
      id: '/_authenticated/_learner/vocabularies/$vocabularyId'
      path: '/$vocabularyId'
      fullPath: '/vocabularies/$vocabularyId'
      preLoaderRoute: typeof AuthenticatedLearnerVocabulariesVocabularyIdRouteImport
      parentRoute: typeof AuthenticatedLearnerVocabulariesRoute
    }
    '/_authenticated/_learner/wordbooks/': {
      id: '/_authenticated/_learner/wordbooks/'
      path: '/wordbooks'
      fullPath: '/wordbooks/'
      preLoaderRoute: typeof AuthenticatedLearnerWordbooksIndexRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/wordbooks/$wordbookId': {
      id: '/_authenticated/_learner/wordbooks/$wordbookId'
      path: '/wordbooks/$wordbookId'
      fullPath: '/wordbooks/$wordbookId'
      preLoaderRoute: typeof AuthenticatedLearnerWordbooksWordbookIdRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/admin/_enrolled/': {
      id: '/_authenticated/admin/_enrolled/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledRoute
    }
    '/_authenticated/admin/_enrolled/content-error-reports': {
      id: '/_authenticated/admin/_enrolled/content-error-reports'
      path: '/content-error-reports'
      fullPath: '/admin/content-error-reports'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledContentErrorReportsRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledRoute
    }
    '/_authenticated/admin/_enrolled/content-imports': {
      id: '/_authenticated/admin/_enrolled/content-imports'
      path: '/content-imports'
      fullPath: '/admin/content-imports'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledContentImportsRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledRoute
    }
    '/_authenticated/admin/_enrolled/questions': {
      id: '/_authenticated/admin/_enrolled/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledRoute
    }
    '/_authenticated/admin/_enrolled/users': {
      id: '/_authenticated/admin/_enrolled/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledUsersRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledRoute
    }
    '/_authenticated/admin/_enrolled/vocabularies': {
      id: '/_authenticated/admin/_enrolled/vocabularies'
      path: '/vocabularies'
      fullPath: '/admin/vocabularies'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledVocabulariesRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledRoute
    }
    '/_authenticated/admin/_enrollment/totp-setup': {
      id: '/_authenticated/admin/_enrollment/totp-setup'
      path: '/totp-setup'
      fullPath: '/admin/totp-setup'
      preLoaderRoute: typeof AuthenticatedAdminEnrollmentTotpSetupRouteImport
      parentRoute: typeof AuthenticatedAdminEnrollmentRoute
    }
    '/_authenticated/_learner/practice/$sessionId/result': {
      id: '/_authenticated/_learner/practice/$sessionId/result'
      path: '/result'
      fullPath: '/practice/$sessionId/result'
      preLoaderRoute: typeof AuthenticatedLearnerPracticeSessionIdResultRouteImport
      parentRoute: typeof AuthenticatedLearnerPracticeSessionIdRoute
    }
    '/_authenticated/admin/_enrolled/concepts/': {
      id: '/_authenticated/admin/_enrolled/concepts/'
      path: '/concepts'
      fullPath: '/admin/concepts/'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledConceptsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledRoute
    }
    '/_authenticated/admin/_enrolled/concepts/$conceptId': {
      id: '/_authenticated/admin/_enrolled/concepts/$conceptId'
      path: '/concepts/$conceptId'
      fullPath: '/admin/concepts/$conceptId'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledConceptsConceptIdRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledRoute
    }
    '/_authenticated/admin/_enrolled/content-imports/': {
      id: '/_authenticated/admin/_enrolled/content-imports/'
      path: '/'
      fullPath: '/admin/content-imports/'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledContentImportsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledContentImportsRoute
    }
    '/_authenticated/admin/_enrolled/content-imports/$importId': {
      id: '/_authenticated/admin/_enrolled/content-imports/$importId'
      path: '/$importId'
      fullPath: '/admin/content-imports/$importId'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledContentImportsImportIdRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledContentImportsRoute
    }
    '/_authenticated/admin/_enrolled/questions/': {
      id: '/_authenticated/admin/_enrolled/questions/'
      path: '/'
      fullPath: '/admin/questions/'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledQuestionsRoute
    }
    '/_authenticated/admin/_enrolled/questions/$questionId': {
      id: '/_authenticated/admin/_enrolled/questions/$questionId'
      path: '/$questionId'
      fullPath: '/admin/questions/$questionId'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledQuestionsRoute
    }
    '/_authenticated/admin/_enrolled/vocabularies/': {
      id: '/_authenticated/admin/_enrolled/vocabularies/'
      path: '/'
      fullPath: '/admin/vocabularies/'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledVocabulariesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledVocabulariesRoute
    }
    '/_authenticated/admin/_enrolled/vocabularies/$vocabularyId': {
      id: '/_authenticated/admin/_enrolled/vocabularies/$vocabularyId'
      path: '/$vocabularyId'
      fullPath: '/admin/vocabularies/$vocabularyId'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledVocabulariesVocabularyIdRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledVocabulariesRoute
    }
    '/_authenticated/admin/_enrolled/questions/$questionId/': {
      id: '/_authenticated/admin/_enrolled/questions/$questionId/'
      path: '/'
      fullPath: '/admin/questions/$questionId/'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdRoute
    }
    '/_authenticated/admin/_enrolled/questions/$questionId/versions/$versionId/replace': {
      id: '/_authenticated/admin/_enrolled/questions/$questionId/versions/$versionId/replace'
      path: '/versions/$versionId/replace'
      fullPath: '/admin/questions/$questionId/versions/$versionId/replace'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdVersionsVersionIdReplaceRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdRoute
    }
  }
}

interface AuthenticatedLearnerQuestionsRouteChildren {
  AuthenticatedLearnerQuestionsQuestionIdRoute: typeof AuthenticatedLearnerQuestionsQuestionIdRoute
  AuthenticatedLearnerQuestionsIndexRoute: typeof AuthenticatedLearnerQuestionsIndexRoute
}

const AuthenticatedLearnerQuestionsRouteChildren: AuthenticatedLearnerQuestionsRouteChildren =
  {
    AuthenticatedLearnerQuestionsQuestionIdRoute:
      AuthenticatedLearnerQuestionsQuestionIdRoute,
    AuthenticatedLearnerQuestionsIndexRoute:
      AuthenticatedLearnerQuestionsIndexRoute,
  }

const AuthenticatedLearnerQuestionsRouteWithChildren =
  AuthenticatedLearnerQuestionsRoute._addFileChildren(
    AuthenticatedLearnerQuestionsRouteChildren,
  )

interface AuthenticatedLearnerVocabulariesRouteChildren {
  AuthenticatedLearnerVocabulariesVocabularyIdRoute: typeof AuthenticatedLearnerVocabulariesVocabularyIdRoute
  AuthenticatedLearnerVocabulariesIndexRoute: typeof AuthenticatedLearnerVocabulariesIndexRoute
}

const AuthenticatedLearnerVocabulariesRouteChildren: AuthenticatedLearnerVocabulariesRouteChildren =
  {
    AuthenticatedLearnerVocabulariesVocabularyIdRoute:
      AuthenticatedLearnerVocabulariesVocabularyIdRoute,
    AuthenticatedLearnerVocabulariesIndexRoute:
      AuthenticatedLearnerVocabulariesIndexRoute,
  }

const AuthenticatedLearnerVocabulariesRouteWithChildren =
  AuthenticatedLearnerVocabulariesRoute._addFileChildren(
    AuthenticatedLearnerVocabulariesRouteChildren,
  )

interface AuthenticatedLearnerPracticeSessionIdRouteChildren {
  AuthenticatedLearnerPracticeSessionIdResultRoute: typeof AuthenticatedLearnerPracticeSessionIdResultRoute
}

const AuthenticatedLearnerPracticeSessionIdRouteChildren: AuthenticatedLearnerPracticeSessionIdRouteChildren =
  {
    AuthenticatedLearnerPracticeSessionIdResultRoute:
      AuthenticatedLearnerPracticeSessionIdResultRoute,
  }

const AuthenticatedLearnerPracticeSessionIdRouteWithChildren =
  AuthenticatedLearnerPracticeSessionIdRoute._addFileChildren(
    AuthenticatedLearnerPracticeSessionIdRouteChildren,
  )

interface AuthenticatedLearnerRouteChildren {
  AuthenticatedLearnerHistoryRoute: typeof AuthenticatedLearnerHistoryRoute
  AuthenticatedLearnerLearnRoute: typeof AuthenticatedLearnerLearnRoute
  AuthenticatedLearnerQuestionsRoute: typeof AuthenticatedLearnerQuestionsRouteWithChildren
  AuthenticatedLearnerVocabulariesRoute: typeof AuthenticatedLearnerVocabulariesRouteWithChildren
  AuthenticatedLearnerConceptsConceptIdRoute: typeof AuthenticatedLearnerConceptsConceptIdRoute
  AuthenticatedLearnerPracticeSessionIdRoute: typeof AuthenticatedLearnerPracticeSessionIdRouteWithChildren
  AuthenticatedLearnerWordbooksWordbookIdRoute: typeof AuthenticatedLearnerWordbooksWordbookIdRoute
  AuthenticatedLearnerConceptsIndexRoute: typeof AuthenticatedLearnerConceptsIndexRoute
  AuthenticatedLearnerPracticeIndexRoute: typeof AuthenticatedLearnerPracticeIndexRoute
  AuthenticatedLearnerWordbooksIndexRoute: typeof AuthenticatedLearnerWordbooksIndexRoute
}

const AuthenticatedLearnerRouteChildren: AuthenticatedLearnerRouteChildren = {
  AuthenticatedLearnerHistoryRoute: AuthenticatedLearnerHistoryRoute,
  AuthenticatedLearnerLearnRoute: AuthenticatedLearnerLearnRoute,
  AuthenticatedLearnerQuestionsRoute:
    AuthenticatedLearnerQuestionsRouteWithChildren,
  AuthenticatedLearnerVocabulariesRoute:
    AuthenticatedLearnerVocabulariesRouteWithChildren,
  AuthenticatedLearnerConceptsConceptIdRoute:
    AuthenticatedLearnerConceptsConceptIdRoute,
  AuthenticatedLearnerPracticeSessionIdRoute:
    AuthenticatedLearnerPracticeSessionIdRouteWithChildren,
  AuthenticatedLearnerWordbooksWordbookIdRoute:
    AuthenticatedLearnerWordbooksWordbookIdRoute,
  AuthenticatedLearnerConceptsIndexRoute:
    AuthenticatedLearnerConceptsIndexRoute,
  AuthenticatedLearnerPracticeIndexRoute:
    AuthenticatedLearnerPracticeIndexRoute,
  AuthenticatedLearnerWordbooksIndexRoute:
    AuthenticatedLearnerWordbooksIndexRoute,
}

const AuthenticatedLearnerRouteWithChildren =
  AuthenticatedLearnerRoute._addFileChildren(AuthenticatedLearnerRouteChildren)

interface AuthenticatedAdminEnrolledContentImportsRouteChildren {
  AuthenticatedAdminEnrolledContentImportsImportIdRoute: typeof AuthenticatedAdminEnrolledContentImportsImportIdRoute
  AuthenticatedAdminEnrolledContentImportsIndexRoute: typeof AuthenticatedAdminEnrolledContentImportsIndexRoute
}

const AuthenticatedAdminEnrolledContentImportsRouteChildren: AuthenticatedAdminEnrolledContentImportsRouteChildren =
  {
    AuthenticatedAdminEnrolledContentImportsImportIdRoute:
      AuthenticatedAdminEnrolledContentImportsImportIdRoute,
    AuthenticatedAdminEnrolledContentImportsIndexRoute:
      AuthenticatedAdminEnrolledContentImportsIndexRoute,
  }

const AuthenticatedAdminEnrolledContentImportsRouteWithChildren =
  AuthenticatedAdminEnrolledContentImportsRoute._addFileChildren(
    AuthenticatedAdminEnrolledContentImportsRouteChildren,
  )

interface AuthenticatedAdminEnrolledQuestionsQuestionIdRouteChildren {
  AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute
  AuthenticatedAdminEnrolledQuestionsQuestionIdVersionsVersionIdReplaceRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdVersionsVersionIdReplaceRoute
}

const AuthenticatedAdminEnrolledQuestionsQuestionIdRouteChildren: AuthenticatedAdminEnrolledQuestionsQuestionIdRouteChildren =
  {
    AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute:
      AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute,
    AuthenticatedAdminEnrolledQuestionsQuestionIdVersionsVersionIdReplaceRoute:
      AuthenticatedAdminEnrolledQuestionsQuestionIdVersionsVersionIdReplaceRoute,
  }

const AuthenticatedAdminEnrolledQuestionsQuestionIdRouteWithChildren =
  AuthenticatedAdminEnrolledQuestionsQuestionIdRoute._addFileChildren(
    AuthenticatedAdminEnrolledQuestionsQuestionIdRouteChildren,
  )

interface AuthenticatedAdminEnrolledQuestionsRouteChildren {
  AuthenticatedAdminEnrolledQuestionsQuestionIdRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdRouteWithChildren
  AuthenticatedAdminEnrolledQuestionsIndexRoute: typeof AuthenticatedAdminEnrolledQuestionsIndexRoute
}

const AuthenticatedAdminEnrolledQuestionsRouteChildren: AuthenticatedAdminEnrolledQuestionsRouteChildren =
  {
    AuthenticatedAdminEnrolledQuestionsQuestionIdRoute:
      AuthenticatedAdminEnrolledQuestionsQuestionIdRouteWithChildren,
    AuthenticatedAdminEnrolledQuestionsIndexRoute:
      AuthenticatedAdminEnrolledQuestionsIndexRoute,
  }

const AuthenticatedAdminEnrolledQuestionsRouteWithChildren =
  AuthenticatedAdminEnrolledQuestionsRoute._addFileChildren(
    AuthenticatedAdminEnrolledQuestionsRouteChildren,
  )

interface AuthenticatedAdminEnrolledVocabulariesRouteChildren {
  AuthenticatedAdminEnrolledVocabulariesVocabularyIdRoute: typeof AuthenticatedAdminEnrolledVocabulariesVocabularyIdRoute
  AuthenticatedAdminEnrolledVocabulariesIndexRoute: typeof AuthenticatedAdminEnrolledVocabulariesIndexRoute
}

const AuthenticatedAdminEnrolledVocabulariesRouteChildren: AuthenticatedAdminEnrolledVocabulariesRouteChildren =
  {
    AuthenticatedAdminEnrolledVocabulariesVocabularyIdRoute:
      AuthenticatedAdminEnrolledVocabulariesVocabularyIdRoute,
    AuthenticatedAdminEnrolledVocabulariesIndexRoute:
      AuthenticatedAdminEnrolledVocabulariesIndexRoute,
  }

const AuthenticatedAdminEnrolledVocabulariesRouteWithChildren =
  AuthenticatedAdminEnrolledVocabulariesRoute._addFileChildren(
    AuthenticatedAdminEnrolledVocabulariesRouteChildren,
  )

interface AuthenticatedAdminEnrolledRouteChildren {
  AuthenticatedAdminEnrolledContentErrorReportsRoute: typeof AuthenticatedAdminEnrolledContentErrorReportsRoute
  AuthenticatedAdminEnrolledContentImportsRoute: typeof AuthenticatedAdminEnrolledContentImportsRouteWithChildren
  AuthenticatedAdminEnrolledQuestionsRoute: typeof AuthenticatedAdminEnrolledQuestionsRouteWithChildren
  AuthenticatedAdminEnrolledUsersRoute: typeof AuthenticatedAdminEnrolledUsersRoute
  AuthenticatedAdminEnrolledVocabulariesRoute: typeof AuthenticatedAdminEnrolledVocabulariesRouteWithChildren
  AuthenticatedAdminEnrolledIndexRoute: typeof AuthenticatedAdminEnrolledIndexRoute
  AuthenticatedAdminEnrolledConceptsConceptIdRoute: typeof AuthenticatedAdminEnrolledConceptsConceptIdRoute
  AuthenticatedAdminEnrolledConceptsIndexRoute: typeof AuthenticatedAdminEnrolledConceptsIndexRoute
}

const AuthenticatedAdminEnrolledRouteChildren: AuthenticatedAdminEnrolledRouteChildren =
  {
    AuthenticatedAdminEnrolledContentErrorReportsRoute:
      AuthenticatedAdminEnrolledContentErrorReportsRoute,
    AuthenticatedAdminEnrolledContentImportsRoute:
      AuthenticatedAdminEnrolledContentImportsRouteWithChildren,
    AuthenticatedAdminEnrolledQuestionsRoute:
      AuthenticatedAdminEnrolledQuestionsRouteWithChildren,
    AuthenticatedAdminEnrolledUsersRoute: AuthenticatedAdminEnrolledUsersRoute,
    AuthenticatedAdminEnrolledVocabulariesRoute:
      AuthenticatedAdminEnrolledVocabulariesRouteWithChildren,
    AuthenticatedAdminEnrolledIndexRoute: AuthenticatedAdminEnrolledIndexRoute,
    AuthenticatedAdminEnrolledConceptsConceptIdRoute:
      AuthenticatedAdminEnrolledConceptsConceptIdRoute,
    AuthenticatedAdminEnrolledConceptsIndexRoute:
      AuthenticatedAdminEnrolledConceptsIndexRoute,
  }

const AuthenticatedAdminEnrolledRouteWithChildren =
  AuthenticatedAdminEnrolledRoute._addFileChildren(
    AuthenticatedAdminEnrolledRouteChildren,
  )

interface AuthenticatedAdminEnrollmentRouteChildren {
  AuthenticatedAdminEnrollmentTotpSetupRoute: typeof AuthenticatedAdminEnrollmentTotpSetupRoute
}

const AuthenticatedAdminEnrollmentRouteChildren: AuthenticatedAdminEnrollmentRouteChildren =
  {
    AuthenticatedAdminEnrollmentTotpSetupRoute:
      AuthenticatedAdminEnrollmentTotpSetupRoute,
  }

const AuthenticatedAdminEnrollmentRouteWithChildren =
  AuthenticatedAdminEnrollmentRoute._addFileChildren(
    AuthenticatedAdminEnrollmentRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEnrolledRoute: typeof AuthenticatedAdminEnrolledRouteWithChildren
  AuthenticatedAdminEnrollmentRoute: typeof AuthenticatedAdminEnrollmentRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEnrolledRoute: AuthenticatedAdminEnrolledRouteWithChildren,
  AuthenticatedAdminEnrollmentRoute:
    AuthenticatedAdminEnrollmentRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLearnerRoute: typeof AuthenticatedLearnerRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLearnerRoute: AuthenticatedLearnerRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginChallengeRoute: typeof LoginChallengeRoute
  LoginConfirmRoute: typeof LoginConfirmRoute
  LoginMfaRoute: typeof LoginMfaRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginChallengeRoute: LoginChallengeRoute,
  LoginConfirmRoute: LoginConfirmRoute,
  LoginMfaRoute: LoginMfaRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
