/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuthenticatedRouteImport } from './app/routes/_authenticated'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as AuthenticatedLearnerRouteImport } from './app/routes/_authenticated._learner'
import { Route as AuthenticatedAdminRouteImport } from './app/routes/_authenticated.admin'
import { Route as LoginIndexRouteImport } from './app/routes/login.index'
import { Route as LoginMfaRouteImport } from './app/routes/login.mfa'
import { Route as AuthenticatedLearnerHistoryRouteImport } from './app/routes/_authenticated._learner.history'
import { Route as AuthenticatedLearnerLearnRouteImport } from './app/routes/_authenticated._learner.learn'
import { Route as AuthenticatedLearnerQuestionsRouteImport } from './app/routes/_authenticated._learner.questions'
import { Route as AuthenticatedLearnerSavedVocabulariesRouteImport } from './app/routes/_authenticated._learner.saved-vocabularies'
import { Route as AuthenticatedLearnerVocabulariesRouteImport } from './app/routes/_authenticated._learner.vocabularies'
import { Route as AuthenticatedAdminEnrolledRouteImport } from './app/routes/_authenticated.admin._enrolled'
import { Route as AuthenticatedAdminEnrollmentRouteImport } from './app/routes/_authenticated.admin._enrollment'
import { Route as AuthenticatedLearnerQuestionsIndexRouteImport } from './app/routes/_authenticated._learner.questions.index'
import { Route as AuthenticatedLearnerQuestionsQuestionIdRouteImport } from './app/routes/_authenticated._learner.questions.$questionId'
import { Route as AuthenticatedLearnerVocabulariesIndexRouteImport } from './app/routes/_authenticated._learner.vocabularies.index'
import { Route as AuthenticatedLearnerVocabulariesVocabularyIdRouteImport } from './app/routes/_authenticated._learner.vocabularies.$vocabularyId'
import { Route as AuthenticatedAdminEnrolledIndexRouteImport } from './app/routes/_authenticated.admin._enrolled.index'
import { Route as AuthenticatedAdminEnrolledContentImportsRouteImport } from './app/routes/_authenticated.admin._enrolled.content-imports'
import { Route as AuthenticatedAdminEnrolledQuestionsRouteImport } from './app/routes/_authenticated.admin._enrolled.questions'
import { Route as AuthenticatedAdminEnrollmentTotpSetupRouteImport } from './app/routes/_authenticated.admin._enrollment.totp-setup'
import { Route as AuthenticatedAdminEnrolledContentImportsIndexRouteImport } from './app/routes/_authenticated.admin._enrolled.content-imports.index'
import { Route as AuthenticatedAdminEnrolledContentImportsImportIdRouteImport } from './app/routes/_authenticated.admin._enrolled.content-imports.$importId'
import { Route as AuthenticatedAdminEnrolledQuestionsIndexRouteImport } from './app/routes/_authenticated.admin._enrolled.questions.index'
import { Route as AuthenticatedAdminEnrolledQuestionsQuestionIdRouteImport } from './app/routes/_authenticated.admin._enrolled.questions.$questionId'
import { Route as AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRouteImport } from './app/routes/_authenticated.admin._enrolled.questions.$questionId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearnerRoute = AuthenticatedLearnerRouteImport.update({
  id: '/_learner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginMfaRoute = LoginMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedLearnerHistoryRoute =
  AuthenticatedLearnerHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerLearnRoute =
  AuthenticatedLearnerLearnRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerQuestionsRoute =
  AuthenticatedLearnerQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerSavedVocabulariesRoute =
  AuthenticatedLearnerSavedVocabulariesRouteImport.update({
    id: '/saved-vocabularies',
    path: '/saved-vocabularies',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedLearnerVocabulariesRoute =
  AuthenticatedLearnerVocabulariesRouteImport.update({
    id: '/vocabularies',
    path: '/vocabularies',
    getParentRoute: () => AuthenticatedLearnerRoute,
  } as any)
const AuthenticatedAdminEnrolledRoute =
  AuthenticatedAdminEnrolledRouteImport.update({
    id: '/_enrolled',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnrollmentRoute =
  AuthenticatedAdminEnrollmentRouteImport.update({
    id: '/_enrollment',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedLearnerQuestionsIndexRoute =
  AuthenticatedLearnerQuestionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLearnerQuestionsRoute,
  } as any)
const AuthenticatedLearnerQuestionsQuestionIdRoute =
  AuthenticatedLearnerQuestionsQuestionIdRouteImport.update({
    id: '/$questionId',
    path: '/$questionId',
    getParentRoute: () => AuthenticatedLearnerQuestionsRoute,
  } as any)
const AuthenticatedLearnerVocabulariesIndexRoute =
  AuthenticatedLearnerVocabulariesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLearnerVocabulariesRoute,
  } as any)
const AuthenticatedLearnerVocabulariesVocabularyIdRoute =
  AuthenticatedLearnerVocabulariesVocabularyIdRouteImport.update({
    id: '/$vocabularyId',
    path: '/$vocabularyId',
    getParentRoute: () => AuthenticatedLearnerVocabulariesRoute,
  } as any)
const AuthenticatedAdminEnrolledIndexRoute =
  AuthenticatedAdminEnrolledIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEnrolledRoute,
  } as any)
const AuthenticatedAdminEnrolledContentImportsRoute =
  AuthenticatedAdminEnrolledContentImportsRouteImport.update({
    id: '/content-imports',
    path: '/content-imports',
    getParentRoute: () => AuthenticatedAdminEnrolledRoute,
  } as any)
const AuthenticatedAdminEnrolledQuestionsRoute =
  AuthenticatedAdminEnrolledQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminEnrolledRoute,
  } as any)
const AuthenticatedAdminEnrollmentTotpSetupRoute =
  AuthenticatedAdminEnrollmentTotpSetupRouteImport.update({
    id: '/totp-setup',
    path: '/totp-setup',
    getParentRoute: () => AuthenticatedAdminEnrollmentRoute,
  } as any)
const AuthenticatedAdminEnrolledContentImportsIndexRoute =
  AuthenticatedAdminEnrolledContentImportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEnrolledContentImportsRoute,
  } as any)
const AuthenticatedAdminEnrolledContentImportsImportIdRoute =
  AuthenticatedAdminEnrolledContentImportsImportIdRouteImport.update({
    id: '/$importId',
    path: '/$importId',
    getParentRoute: () => AuthenticatedAdminEnrolledContentImportsRoute,
  } as any)
const AuthenticatedAdminEnrolledQuestionsIndexRoute =
  AuthenticatedAdminEnrolledQuestionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEnrolledQuestionsRoute,
  } as any)
const AuthenticatedAdminEnrolledQuestionsQuestionIdRoute =
  AuthenticatedAdminEnrolledQuestionsQuestionIdRouteImport.update({
    id: '/$questionId',
    path: '/$questionId',
    getParentRoute: () => AuthenticatedAdminEnrolledQuestionsRoute,
  } as any)
const AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute =
  AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEnrolledQuestionsQuestionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/login/mfa': typeof LoginMfaRoute
  '/login/': typeof LoginIndexRoute
  '/history': typeof AuthenticatedLearnerHistoryRoute
  '/learn': typeof AuthenticatedLearnerLearnRoute
  '/questions': typeof AuthenticatedLearnerQuestionsRouteWithChildren
  '/saved-vocabularies': typeof AuthenticatedLearnerSavedVocabulariesRoute
  '/vocabularies': typeof AuthenticatedLearnerVocabulariesRouteWithChildren
  '/questions/$questionId': typeof AuthenticatedLearnerQuestionsQuestionIdRoute
  '/vocabularies/$vocabularyId': typeof AuthenticatedLearnerVocabulariesVocabularyIdRoute
  '/admin/content-imports': typeof AuthenticatedAdminEnrolledContentImportsRouteWithChildren
  '/admin/questions': typeof AuthenticatedAdminEnrolledQuestionsRouteWithChildren
  '/admin/totp-setup': typeof AuthenticatedAdminEnrollmentTotpSetupRoute
  '/questions/': typeof AuthenticatedLearnerQuestionsIndexRoute
  '/vocabularies/': typeof AuthenticatedLearnerVocabulariesIndexRoute
  '/admin/': typeof AuthenticatedAdminEnrolledIndexRoute
  '/admin/content-imports/$importId': typeof AuthenticatedAdminEnrolledContentImportsImportIdRoute
  '/admin/questions/$questionId': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdRouteWithChildren
  '/admin/content-imports/': typeof AuthenticatedAdminEnrolledContentImportsIndexRoute
  '/admin/questions/': typeof AuthenticatedAdminEnrolledQuestionsIndexRoute
  '/admin/questions/$questionId/': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminEnrolledIndexRoute
  '/login/mfa': typeof LoginMfaRoute
  '/login': typeof LoginIndexRoute
  '/history': typeof AuthenticatedLearnerHistoryRoute
  '/learn': typeof AuthenticatedLearnerLearnRoute
  '/saved-vocabularies': typeof AuthenticatedLearnerSavedVocabulariesRoute
  '/questions/$questionId': typeof AuthenticatedLearnerQuestionsQuestionIdRoute
  '/vocabularies/$vocabularyId': typeof AuthenticatedLearnerVocabulariesVocabularyIdRoute
  '/admin/totp-setup': typeof AuthenticatedAdminEnrollmentTotpSetupRoute
  '/questions': typeof AuthenticatedLearnerQuestionsIndexRoute
  '/vocabularies': typeof AuthenticatedLearnerVocabulariesIndexRoute
  '/admin/content-imports/$importId': typeof AuthenticatedAdminEnrolledContentImportsImportIdRoute
  '/admin/content-imports': typeof AuthenticatedAdminEnrolledContentImportsIndexRoute
  '/admin/questions': typeof AuthenticatedAdminEnrolledQuestionsIndexRoute
  '/admin/questions/$questionId': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_authenticated/_learner': typeof AuthenticatedLearnerRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/login/mfa': typeof LoginMfaRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/_learner/history': typeof AuthenticatedLearnerHistoryRoute
  '/_authenticated/_learner/learn': typeof AuthenticatedLearnerLearnRoute
  '/_authenticated/_learner/questions': typeof AuthenticatedLearnerQuestionsRouteWithChildren
  '/_authenticated/_learner/saved-vocabularies': typeof AuthenticatedLearnerSavedVocabulariesRoute
  '/_authenticated/_learner/vocabularies': typeof AuthenticatedLearnerVocabulariesRouteWithChildren
  '/_authenticated/admin/_enrolled': typeof AuthenticatedAdminEnrolledRouteWithChildren
  '/_authenticated/admin/_enrollment': typeof AuthenticatedAdminEnrollmentRouteWithChildren
  '/_authenticated/_learner/questions/$questionId': typeof AuthenticatedLearnerQuestionsQuestionIdRoute
  '/_authenticated/_learner/vocabularies/$vocabularyId': typeof AuthenticatedLearnerVocabulariesVocabularyIdRoute
  '/_authenticated/admin/_enrolled/content-imports': typeof AuthenticatedAdminEnrolledContentImportsRouteWithChildren
  '/_authenticated/admin/_enrolled/questions': typeof AuthenticatedAdminEnrolledQuestionsRouteWithChildren
  '/_authenticated/admin/_enrollment/totp-setup': typeof AuthenticatedAdminEnrollmentTotpSetupRoute
  '/_authenticated/_learner/questions/': typeof AuthenticatedLearnerQuestionsIndexRoute
  '/_authenticated/_learner/vocabularies/': typeof AuthenticatedLearnerVocabulariesIndexRoute
  '/_authenticated/admin/_enrolled/': typeof AuthenticatedAdminEnrolledIndexRoute
  '/_authenticated/admin/_enrolled/content-imports/$importId': typeof AuthenticatedAdminEnrolledContentImportsImportIdRoute
  '/_authenticated/admin/_enrolled/questions/$questionId': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdRouteWithChildren
  '/_authenticated/admin/_enrolled/content-imports/': typeof AuthenticatedAdminEnrolledContentImportsIndexRoute
  '/_authenticated/admin/_enrolled/questions/': typeof AuthenticatedAdminEnrolledQuestionsIndexRoute
  '/_authenticated/admin/_enrolled/questions/$questionId/': typeof AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/login/mfa'
    | '/login/'
    | '/history'
    | '/learn'
    | '/questions'
    | '/saved-vocabularies'
    | '/vocabularies'
    | '/questions/$questionId'
    | '/vocabularies/$vocabularyId'
    | '/admin/content-imports'
    | '/admin/questions'
    | '/admin/totp-setup'
    | '/questions/'
    | '/vocabularies/'
    | '/admin/'
    | '/admin/content-imports/$importId'
    | '/admin/questions/$questionId'
    | '/admin/content-imports/'
    | '/admin/questions/'
    | '/admin/questions/$questionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login/mfa'
    | '/login'
    | '/history'
    | '/learn'
    | '/saved-vocabularies'
    | '/questions/$questionId'
    | '/vocabularies/$vocabularyId'
    | '/admin/totp-setup'
    | '/questions'
    | '/vocabularies'
    | '/admin/content-imports/$importId'
    | '/admin/content-imports'
    | '/admin/questions'
    | '/admin/questions/$questionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_learner'
    | '/_authenticated/admin'
    | '/login/mfa'
    | '/login/'
    | '/_authenticated/_learner/history'
    | '/_authenticated/_learner/learn'
    | '/_authenticated/_learner/questions'
    | '/_authenticated/_learner/saved-vocabularies'
    | '/_authenticated/_learner/vocabularies'
    | '/_authenticated/admin/_enrolled'
    | '/_authenticated/admin/_enrollment'
    | '/_authenticated/_learner/questions/$questionId'
    | '/_authenticated/_learner/vocabularies/$vocabularyId'
    | '/_authenticated/admin/_enrolled/content-imports'
    | '/_authenticated/admin/_enrolled/questions'
    | '/_authenticated/admin/_enrollment/totp-setup'
    | '/_authenticated/_learner/questions/'
    | '/_authenticated/_learner/vocabularies/'
    | '/_authenticated/admin/_enrolled/'
    | '/_authenticated/admin/_enrolled/content-imports/$importId'
    | '/_authenticated/admin/_enrolled/questions/$questionId'
    | '/_authenticated/admin/_enrolled/content-imports/'
    | '/_authenticated/admin/_enrolled/questions/'
    | '/_authenticated/admin/_enrolled/questions/$questionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_learner': {
      id: '/_authenticated/_learner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLearnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/mfa': {
      id: '/login/mfa'
      path: '/mfa'
      fullPath: '/login/mfa'
      preLoaderRoute: typeof LoginMfaRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/_learner/history': {
      id: '/_authenticated/_learner/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedLearnerHistoryRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/learn': {
      id: '/_authenticated/_learner/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnerLearnRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/questions': {
      id: '/_authenticated/_learner/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedLearnerQuestionsRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/saved-vocabularies': {
      id: '/_authenticated/_learner/saved-vocabularies'
      path: '/saved-vocabularies'
      fullPath: '/saved-vocabularies'
      preLoaderRoute: typeof AuthenticatedLearnerSavedVocabulariesRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/_learner/vocabularies': {
      id: '/_authenticated/_learner/vocabularies'
      path: '/vocabularies'
      fullPath: '/vocabularies'
      preLoaderRoute: typeof AuthenticatedLearnerVocabulariesRouteImport
      parentRoute: typeof AuthenticatedLearnerRoute
    }
    '/_authenticated/admin/_enrolled': {
      id: '/_authenticated/admin/_enrolled'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/_enrollment': {
      id: '/_authenticated/admin/_enrollment'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminEnrollmentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_learner/questions/': {
      id: '/_authenticated/_learner/questions/'
      path: '/'
      fullPath: '/questions/'
      preLoaderRoute: typeof AuthenticatedLearnerQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedLearnerQuestionsRoute
    }
    '/_authenticated/_learner/questions/$questionId': {
      id: '/_authenticated/_learner/questions/$questionId'
      path: '/$questionId'
      fullPath: '/questions/$questionId'
      preLoaderRoute: typeof AuthenticatedLearnerQuestionsQuestionIdRouteImport
      parentRoute: typeof AuthenticatedLearnerQuestionsRoute
    }
    '/_authenticated/_learner/vocabularies/': {
      id: '/_authenticated/_learner/vocabularies/'
      path: '/'
      fullPath: '/vocabularies/'
      preLoaderRoute: typeof AuthenticatedLearnerVocabulariesIndexRouteImport
      parentRoute: typeof AuthenticatedLearnerVocabulariesRoute
    }
    '/_authenticated/_learner/vocabularies/$vocabularyId': {
      id: '/_authenticated/_learner/vocabularies/$vocabularyId'
      path: '/$vocabularyId'
      fullPath: '/vocabularies/$vocabularyId'
      preLoaderRoute: typeof AuthenticatedLearnerVocabulariesVocabularyIdRouteImport
      parentRoute: typeof AuthenticatedLearnerVocabulariesRoute
    }
    '/_authenticated/admin/_enrolled/': {
      id: '/_authenticated/admin/_enrolled/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledRoute
    }
    '/_authenticated/admin/_enrolled/content-imports': {
      id: '/_authenticated/admin/_enrolled/content-imports'
      path: '/content-imports'
      fullPath: '/admin/content-imports'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledContentImportsRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledRoute
    }
    '/_authenticated/admin/_enrolled/questions': {
      id: '/_authenticated/admin/_enrolled/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledRoute
    }
    '/_authenticated/admin/_enrollment/totp-setup': {
      id: '/_authenticated/admin/_enrollment/totp-setup'
      path: '/totp-setup'
      fullPath: '/admin/totp-setup'
      preLoaderRoute: typeof AuthenticatedAdminEnrollmentTotpSetupRouteImport
      parentRoute: typeof AuthenticatedAdminEnrollmentRoute
    }
    '/_authenticated/admin/_enrolled/content-imports/': {
      id: '/_authenticated/admin/_enrolled/content-imports/'
      path: '/'
      fullPath: '/admin/content-imports/'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledContentImportsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledContentImportsRoute
    }
    '/_authenticated/admin/_enrolled/content-imports/$importId': {
      id: '/_authenticated/admin/_enrolled/content-imports/$importId'
      path: '/$importId'
      fullPath: '/admin/content-imports/$importId'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledContentImportsImportIdRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledContentImportsRoute
    }
    '/_authenticated/admin/_enrolled/questions/': {
      id: '/_authenticated/admin/_enrolled/questions/'
      path: '/'
      fullPath: '/admin/questions/'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledQuestionsRoute
    }
    '/_authenticated/admin/_enrolled/questions/$questionId': {
      id: '/_authenticated/admin/_enrolled/questions/$questionId'
      path: '/$questionId'
      fullPath: '/admin/questions/$questionId'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledQuestionsRoute
    }
    '/_authenticated/admin/_enrolled/questions/$questionId/': {
      id: '/_authenticated/admin/_enrolled/questions/$questionId/'
      path: '/'
      fullPath: '/admin/questions/$questionId/'
      preLoaderRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdRoute
    }
  }
}

interface AuthenticatedLearnerQuestionsRouteChildren {
  AuthenticatedLearnerQuestionsQuestionIdRoute: typeof AuthenticatedLearnerQuestionsQuestionIdRoute
  AuthenticatedLearnerQuestionsIndexRoute: typeof AuthenticatedLearnerQuestionsIndexRoute
}

const AuthenticatedLearnerQuestionsRouteChildren: AuthenticatedLearnerQuestionsRouteChildren =
  {
    AuthenticatedLearnerQuestionsQuestionIdRoute:
      AuthenticatedLearnerQuestionsQuestionIdRoute,
    AuthenticatedLearnerQuestionsIndexRoute:
      AuthenticatedLearnerQuestionsIndexRoute,
  }

const AuthenticatedLearnerQuestionsRouteWithChildren =
  AuthenticatedLearnerQuestionsRoute._addFileChildren(
    AuthenticatedLearnerQuestionsRouteChildren,
  )

interface AuthenticatedLearnerVocabulariesRouteChildren {
  AuthenticatedLearnerVocabulariesVocabularyIdRoute: typeof AuthenticatedLearnerVocabulariesVocabularyIdRoute
  AuthenticatedLearnerVocabulariesIndexRoute: typeof AuthenticatedLearnerVocabulariesIndexRoute
}

const AuthenticatedLearnerVocabulariesRouteChildren: AuthenticatedLearnerVocabulariesRouteChildren =
  {
    AuthenticatedLearnerVocabulariesVocabularyIdRoute:
      AuthenticatedLearnerVocabulariesVocabularyIdRoute,
    AuthenticatedLearnerVocabulariesIndexRoute:
      AuthenticatedLearnerVocabulariesIndexRoute,
  }

const AuthenticatedLearnerVocabulariesRouteWithChildren =
  AuthenticatedLearnerVocabulariesRoute._addFileChildren(
    AuthenticatedLearnerVocabulariesRouteChildren,
  )

interface AuthenticatedLearnerRouteChildren {
  AuthenticatedLearnerHistoryRoute: typeof AuthenticatedLearnerHistoryRoute
  AuthenticatedLearnerLearnRoute: typeof AuthenticatedLearnerLearnRoute
  AuthenticatedLearnerQuestionsRoute: typeof AuthenticatedLearnerQuestionsRouteWithChildren
  AuthenticatedLearnerSavedVocabulariesRoute: typeof AuthenticatedLearnerSavedVocabulariesRoute
  AuthenticatedLearnerVocabulariesRoute: typeof AuthenticatedLearnerVocabulariesRouteWithChildren
}

const AuthenticatedLearnerRouteChildren: AuthenticatedLearnerRouteChildren = {
  AuthenticatedLearnerHistoryRoute: AuthenticatedLearnerHistoryRoute,
  AuthenticatedLearnerLearnRoute: AuthenticatedLearnerLearnRoute,
  AuthenticatedLearnerQuestionsRoute:
    AuthenticatedLearnerQuestionsRouteWithChildren,
  AuthenticatedLearnerSavedVocabulariesRoute:
    AuthenticatedLearnerSavedVocabulariesRoute,
  AuthenticatedLearnerVocabulariesRoute:
    AuthenticatedLearnerVocabulariesRouteWithChildren,
}

const AuthenticatedLearnerRouteWithChildren =
  AuthenticatedLearnerRoute._addFileChildren(AuthenticatedLearnerRouteChildren)

interface AuthenticatedAdminEnrolledContentImportsRouteChildren {
  AuthenticatedAdminEnrolledContentImportsImportIdRoute: typeof AuthenticatedAdminEnrolledContentImportsImportIdRoute
  AuthenticatedAdminEnrolledContentImportsIndexRoute: typeof AuthenticatedAdminEnrolledContentImportsIndexRoute
}

const AuthenticatedAdminEnrolledContentImportsRouteChildren: AuthenticatedAdminEnrolledContentImportsRouteChildren =
  {
    AuthenticatedAdminEnrolledContentImportsImportIdRoute:
      AuthenticatedAdminEnrolledContentImportsImportIdRoute,
    AuthenticatedAdminEnrolledContentImportsIndexRoute:
      AuthenticatedAdminEnrolledContentImportsIndexRoute,
  }

const AuthenticatedAdminEnrolledContentImportsRouteWithChildren =
  AuthenticatedAdminEnrolledContentImportsRoute._addFileChildren(
    AuthenticatedAdminEnrolledContentImportsRouteChildren,
  )

interface AuthenticatedAdminEnrolledQuestionsQuestionIdRouteChildren {
  AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute
}

const AuthenticatedAdminEnrolledQuestionsQuestionIdRouteChildren: AuthenticatedAdminEnrolledQuestionsQuestionIdRouteChildren =
  {
    AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute:
      AuthenticatedAdminEnrolledQuestionsQuestionIdIndexRoute,
  }

const AuthenticatedAdminEnrolledQuestionsQuestionIdRouteWithChildren =
  AuthenticatedAdminEnrolledQuestionsQuestionIdRoute._addFileChildren(
    AuthenticatedAdminEnrolledQuestionsQuestionIdRouteChildren,
  )

interface AuthenticatedAdminEnrolledQuestionsRouteChildren {
  AuthenticatedAdminEnrolledQuestionsQuestionIdRoute: typeof AuthenticatedAdminEnrolledQuestionsQuestionIdRouteWithChildren
  AuthenticatedAdminEnrolledQuestionsIndexRoute: typeof AuthenticatedAdminEnrolledQuestionsIndexRoute
}

const AuthenticatedAdminEnrolledQuestionsRouteChildren: AuthenticatedAdminEnrolledQuestionsRouteChildren =
  {
    AuthenticatedAdminEnrolledQuestionsQuestionIdRoute:
      AuthenticatedAdminEnrolledQuestionsQuestionIdRouteWithChildren,
    AuthenticatedAdminEnrolledQuestionsIndexRoute:
      AuthenticatedAdminEnrolledQuestionsIndexRoute,
  }

const AuthenticatedAdminEnrolledQuestionsRouteWithChildren =
  AuthenticatedAdminEnrolledQuestionsRoute._addFileChildren(
    AuthenticatedAdminEnrolledQuestionsRouteChildren,
  )

interface AuthenticatedAdminEnrolledRouteChildren {
  AuthenticatedAdminEnrolledContentImportsRoute: typeof AuthenticatedAdminEnrolledContentImportsRouteWithChildren
  AuthenticatedAdminEnrolledQuestionsRoute: typeof AuthenticatedAdminEnrolledQuestionsRouteWithChildren
  AuthenticatedAdminEnrolledIndexRoute: typeof AuthenticatedAdminEnrolledIndexRoute
}

const AuthenticatedAdminEnrolledRouteChildren: AuthenticatedAdminEnrolledRouteChildren =
  {
    AuthenticatedAdminEnrolledContentImportsRoute:
      AuthenticatedAdminEnrolledContentImportsRouteWithChildren,
    AuthenticatedAdminEnrolledQuestionsRoute:
      AuthenticatedAdminEnrolledQuestionsRouteWithChildren,
    AuthenticatedAdminEnrolledIndexRoute: AuthenticatedAdminEnrolledIndexRoute,
  }

const AuthenticatedAdminEnrolledRouteWithChildren =
  AuthenticatedAdminEnrolledRoute._addFileChildren(
    AuthenticatedAdminEnrolledRouteChildren,
  )

interface AuthenticatedAdminEnrollmentRouteChildren {
  AuthenticatedAdminEnrollmentTotpSetupRoute: typeof AuthenticatedAdminEnrollmentTotpSetupRoute
}

const AuthenticatedAdminEnrollmentRouteChildren: AuthenticatedAdminEnrollmentRouteChildren =
  {
    AuthenticatedAdminEnrollmentTotpSetupRoute:
      AuthenticatedAdminEnrollmentTotpSetupRoute,
  }

const AuthenticatedAdminEnrollmentRouteWithChildren =
  AuthenticatedAdminEnrollmentRoute._addFileChildren(
    AuthenticatedAdminEnrollmentRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEnrolledRoute: typeof AuthenticatedAdminEnrolledRouteWithChildren
  AuthenticatedAdminEnrollmentRoute: typeof AuthenticatedAdminEnrollmentRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEnrolledRoute: AuthenticatedAdminEnrolledRouteWithChildren,
  AuthenticatedAdminEnrollmentRoute:
    AuthenticatedAdminEnrollmentRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLearnerRoute: typeof AuthenticatedLearnerRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLearnerRoute: AuthenticatedLearnerRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginMfaRoute: typeof LoginMfaRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginMfaRoute: LoginMfaRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
