/** Wave 5 도메인 공개 진입점이 신규 AI 문제·TTS 모델과 port를 노출하는지 검증한다 */
import {
  ContentTtsReadinessError,
  QuestionCandidateReviewError,
  QuestionCandidateReviewService,
  TtsDomainError,
  assertContentTtsReady,
  buildQuestionGenerationPrompt,
  classifyQuestionCandidate,
  createTtsCacheKey,
} from '@flex-thia/domain';
import type * as Domain from '@flex-thia/domain';
import { describe, expect, expectTypeOf, it } from 'vitest';

type Wave5DomainBoundary = [
  Domain.QuestionCandidateGroup,
  Domain.QuestionCandidateReviewStatus,
  Domain.QuestionValidationStage,
  Domain.GeneratedQuestionSentenceInput,
  Domain.GeneratedQuestionOptionInput,
  Domain.GeneratedQuestionPayload,
  Domain.GeneratedQuestionCandidate,
  Domain.StoredQuestionCandidateSnapshot,
  Domain.QuestionProductionProviderCandidate,
  Domain.QuestionProductionValidationRecord,
  Domain.QuestionProductionCandidateRecord,
  Domain.QuestionProductionArtifacts,
  Domain.QuestionValidationResult,
  Domain.QuestionCandidateClassification,
  Domain.QuestionPromptVocabulary,
  Domain.QuestionSimilaritySummary,
  Domain.QuestionPromptApprovedExample,
  Domain.QuestionProductionContext,
  Domain.QuestionGenerationPrompt,
  Domain.QuestionGenerationInput,
  Domain.QuestionGenerationResult,
  Domain.QuestionCrossValidationInput,
  Domain.QuestionCrossValidationResult,
  Domain.QuestionProductionProviderExecution,
  Domain.QuestionProductionProviderResult,
  Domain.QuestionProductionProviderFailure,
  Domain.QuestionGenerationProvider,
  Domain.QuestionCrossValidationProvider,
  Domain.QuestionProductionProviderRunRepository,
  Domain.QuestionProductionContextRepository,
  Domain.QuestionProductionCandidateRepository,
  Domain.QuestionSimilarityMatch,
  Domain.QuestionSimilarityLookup,
  Domain.QuestionCandidateReviewCommand,
  Domain.DiscardQuestionCandidateInput,
  Domain.RegenerateQuestionCandidateInput,
  Domain.QuestionRegenerationDispatchInput,
  Domain.GeneratedQuestionDraftRepository,
  Domain.QuestionRegenerationDispatchWriter,
  Domain.ApproveQuestionCandidateInput,
  Domain.ApprovedQuestionDraft,
  Domain.TtsTargetKind,
  Domain.TtsItemStatus,
  Domain.TtsJobStatus,
  Domain.TtsPublishableContent,
  Domain.ContentTtsMediaStatus,
  Domain.ContentTtsReadinessTarget,
  Domain.TtsTargetSnapshot,
  Domain.TtsJob,
  Domain.TtsItem,
  Domain.CreateTtsJobInput,
  Domain.TtsJobListInput,
  Domain.TtsItemListInput,
  Domain.TtsJobCounts,
  Domain.TtsJobPage,
  Domain.TtsJobDetail,
  Domain.TtsItemPage,
  Domain.TtsWorkItem,
  Domain.TtsVoiceSnapshot,
  Domain.TtsSuccessInput,
  Domain.TtsFailureInput,
  Domain.RetryTtsItemsInput,
  Domain.ClaimTtsItemInput,
  Domain.ContentTtsReadinessRepository,
  Domain.TtsProviderResult,
  Domain.TtsProvider,
  Domain.TtsAudioStore,
  Domain.TtsTargetAttachmentRepository,
];

describe('Wave 5 domain 공개 import', () => {
  it('패키지 루트가 AI 문제와 TTS 모델·port를 공개한다', () => {
    expectTypeOf<Wave5DomainBoundary>().toBeArray();
    expect([
      ContentTtsReadinessError,
      QuestionCandidateReviewError,
      QuestionCandidateReviewService,
      TtsDomainError,
      assertContentTtsReady,
      buildQuestionGenerationPrompt,
      classifyQuestionCandidate,
      createTtsCacheKey,
    ]).not.toContain(undefined);
  });
});
