CREATE TYPE "public"."vocabulary_candidate_resolution_kind" AS ENUM('DRAFT_CREATED', 'EXISTING_LINKED');--> statement-breakpoint
CREATE TYPE "public"."vocabulary_candidate_review_status" AS ENUM('PENDING', 'APPROVED', 'DISCARDED');--> statement-breakpoint
ALTER TABLE "vocabulary_production_candidates" ADD COLUMN "review_status" "vocabulary_candidate_review_status" DEFAULT 'PENDING' NOT NULL;--> statement-breakpoint
ALTER TABLE "vocabulary_production_candidates" ADD COLUMN "revision" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "vocabulary_production_candidates" ADD COLUMN "resolution_kind" "vocabulary_candidate_resolution_kind";--> statement-breakpoint
ALTER TABLE "vocabulary_production_candidates" ADD COLUMN "resolved_vocabulary_id" uuid;--> statement-breakpoint
ALTER TABLE "vocabulary_production_candidates" ADD COLUMN "reviewed_by" uuid;--> statement-breakpoint
ALTER TABLE "vocabulary_production_candidates" ADD COLUMN "reviewed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "vocabulary_production_candidates" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "vocabulary_production_candidates" ADD CONSTRAINT "vocabulary_production_candidates_resolved_vocabulary_id_vocabularies_id_fk" FOREIGN KEY ("resolved_vocabulary_id") REFERENCES "public"."vocabularies"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vocabulary_production_candidates" ADD CONSTRAINT "vocabulary_production_candidates_reviewed_by_users_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vocabulary_production_candidates" ADD CONSTRAINT "vocabulary_production_candidates_revision_nonnegative" CHECK ("vocabulary_production_candidates"."revision" >= 0);--> statement-breakpoint
ALTER TABLE "vocabulary_production_candidates" ADD CONSTRAINT "vocabulary_production_candidates_review_resolution_consistency" CHECK (("vocabulary_production_candidates"."review_status" = 'PENDING' and "vocabulary_production_candidates"."resolution_kind" is null and "vocabulary_production_candidates"."resolved_vocabulary_id" is null and "vocabulary_production_candidates"."reviewed_by" is null and "vocabulary_production_candidates"."reviewed_at" is null) or ("vocabulary_production_candidates"."review_status" = 'APPROVED' and "vocabulary_production_candidates"."resolution_kind" is not null and "vocabulary_production_candidates"."resolved_vocabulary_id" is not null and "vocabulary_production_candidates"."reviewed_by" is not null and "vocabulary_production_candidates"."reviewed_at" is not null) or ("vocabulary_production_candidates"."review_status" = 'DISCARDED' and "vocabulary_production_candidates"."resolution_kind" is null and "vocabulary_production_candidates"."resolved_vocabulary_id" is null and "vocabulary_production_candidates"."reviewed_by" is not null and "vocabulary_production_candidates"."reviewed_at" is not null));